### PR TITLE
New style

### PR DESCRIPTION
**Pull request by hacdias**
This implements https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/12. Screenshots will be added as progress is made.

- [ ] Requires https://github.com/ipfs-shipyard/ipfs-css/pull/3.

### CODE REVIEW

**Comment by hacdias** [comment]
@ipfs-shipyard/ipfs-gui-team the progress of this PR:

image

image

😄

**Comment by hacdias** [comment]
@akrych the search field should allow us to search for file names on our MFS and Pinned Hashes?

**Comment by akrych** [comment]
@hacdias 

> @akrych the search field should allow us to search for file names on our MFS and Pinned Hashes?
yes:)

**Comment by hacdias** [comment]
image

@akrych, I've got some questions (yey! 😄):

1. About (number 1): should we use toggles or checkboxes there? Either way, I'll use the styles from [IPFS Web GUI Kit](https://app.zeplin.io/project/5a32d45d1a17248135241058/screen/5a61ef47ed52e04990db4b9a).
2. Do you like the settings? Do you have suggestions? What should I change?
3. Do you already have the icons we talked about on Friday available (settings and power with the same size, and tick/cancel without the circle).

Thanks 😄

**Comment by hacdias** [comment]
@ipfs-shipyard/ipfs-gui-team more screenshots_

image

image

That's it 😄

**Comment by hacdias** [comment]
One more thing @akrych: as you can see from the screenshots above, the Peer ID is too long to be shown in one line. Should I decrease the font size **or** put in the next line?

**Pull request closed without merging**
