### PR TITLE
feat: default minimum and maximum connections

### PR DESCRIPTION
**Pull request by hacdias**
Set the range to 200-300. The default was 300-600. Ref: #665

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by olizilla** [comment]
I'm in favour of this change, but for posterity, we should replace it with a desktop profile in IPFS core when it is available https://github.com/ipfs/go-ipfs/issues/4989

**Comment by olizilla** [comment]
@lidel good news, the logic only runs on init!

https://github.com/ipfs-shipyard/ipfs-desktop/blob/62317e02bb6f534c5806c0c6c204bfacf09999e7/src/utils/daemon.js#L39-L41

**Comment by olizilla** [comment]
From @whyrusleeping notes it sounds like we should set the `ConnMgr` values to

```json
"LowWater": 50,
"HighWater": 200,
"GracePeriod": "300s"
```

Otherwise
- `Discovery.MDNS.enabled is `true` by default
- `DisableNatPortMap` is `false` by default

but we could explicitly set them here. I'm not sure what we'd need to change to ensure

> relay addresses should be advertised

**Comment by hacdias** [comment]
Merging this now with the defaults decided here. Let's hope a desktop profile is created soon so we can just use it! 😄

**Pull request merged**
