### PR TITLE
feat: apple guidelines macOS compliant icon

### PR DESCRIPTION
**Pull request by hacdias**
After much discussion on #956, I decided to keep it simple and just change the menubar icon on macOS since it is the only platform where we are actually violating the guidelines.

Secondly, after a lot of discussion (again!) about how to differentiate between an online and offline node, I decided to go with the most simple solution and follow what some other tools do: just dim the icon when it's offline

@ericronne I used your last icon. However, I needed to **resize** it because it had a lot of white space surrounding it. Since it's a real pixel perfect work, I ask you to take a look at this screenshots to see if they look good or not, please.

Screenshot 2019-11-22 at 06 13 41
Screenshot 2019-11-22 at 06 13 36
Screenshot 2019-11-22 at 06 13 29
Screenshot 2019-11-22 at 06 13 21

### CODE REVIEW

**Comment by lidel** [comment]
If we use dimming for status, do we still need dots in corners?
Perhaps a simple cube would be enough.

**Comment by hacdias** [comment]
@lidel it works for me. Wdyt @ericronne ?

**Comment by ericronne** [comment]
Sure, thx!

**Comment by hacdias** [comment]
@ericronne could you make a small cube icon with stronger outlines so we can apply it here, please?

**Comment by ericronne** [comment]
Here's both a plain option one with node dots on the corners. The plain version better represents the most widely used ipfs logo, but it's also more generic ...
image
**[plain .svg](https://drive.google.com/open?id=1xqcFvaeuPmZoQy1Zm2tJhzFkTQnIxY3Z)**

I'd recommend the dotted version …
image
**[dotted .svg](https://drive.google.com/open?id=1VWG9c3-U6dnGBgVr1u1UxZbxWqvoYXpz)**

**Comment by hacdias** [comment]
Let's vote!

:tada: for

image

:rocket: for

image

**Comment by hacdias** [comment]
PS: our icon is perfectly centered. Other might not and cause the sensation of not being centered.

**Comment by autonome** [comment]
In isolation and enlarged, the dotted version looks ok. However, when in the menubar it no longer looks easily recognizable as IPFS - the large dots make it look circular, a bit like a ship's wheel.

I recommend using either the generic-but-more-obviously-IPFS icon or experimenting with smaller dots.

**Comment by hacdias** [comment]
Say hello to the winner and to the next "generation" IPFS Desktop on macOS icon:

image

**Pull request merged**
