### PR TITLE
fixes: use debug, correctly open settings and offline stats

### PR DESCRIPTION
**Pull request by hacdias**
- [x] Use `debugger` instead of Winston.
- [x] Open the settings with `openItem` instead of `openExternal`.
- [x] Fixes offline stats.

**Edit:** just noticed that the daemon is always exiting with error on Windows.

### CODE REVIEW

**Comment by hacdias** [comment]
@VictorBjelkholm can you try running this branch to see if you "Node Settings" already work? 😄

**Comment by VictorBjelkholm** [comment]
I downloaded the .deb from https://ci.ipfs.team/blue/organizations/jenkins/IPFS%20Shipyard%2Fipfs-desktop/detail/PR-585/4/artifacts

First problem I hit was that I was running go-ipfs since before and ipfs-station just refused to start up. It should reuse the already running daemon if it exists.

Second issue I hit was that all the values were undefined since I wasn't connected to the internet. It should still list the Node ID, even though I cannot reach the internet.

Thirdly, "Node Settings" does open up a editor for editing the settings now.

**Comment by hacdias** [comment]
@VictorBjelkholm 

> First problem I hit was that I was running go-ipfs since before and ipfs-station just refused to start up. It should reuse the already running daemon if it exists.

Ref.: #542. Will be easier after #549 gets merged.

> Second issue I hit was that all the values were undefined since I wasn't connected to the internet. It should still list the Node ID, even though I cannot reach the internet.

Gonna check this tomorrow. 😄 

> Thirdly, "Node Settings" does open up a editor for editing the settings now.

Awesome!

> Not sure ^ is new things, but things I noticed was broken in the build for this PR.

Sometimes the build just fails... I'll restart it.

**Comment by hacdias** [comment]
@VictorBjelkholm btw, you can now run this with `DEBUG=desktop yarn start` to see the log. Could you check if you can find out the reason why IPFS is being killed now?

**Pull request merged**
