### PR TITLE
Fixes Bunch

### LINKED ISSUE #588: Remove repo.lock if not running
Before starting the node, check if it is already running and, if not, remove the `repo.lock` file.

Do after #542

### LINKED ISSUE #590: No files listed on new install with existing repo
Just installed IPFS Desktop (Amazing work, it is rad!). I've got an existing repo, and the node stats show i'm sharing a bunch of things

screenshot 2018-01-11 09 38 55

But the files panel shows an empty list, which is surprising.

screenshot 2018-01-11 09 38 59

This is on:

- OSX 10.12.6
- IPFS Desktop 0.3
- go-ipfs 0.4.11

### LINKED ISSUE #599: Addresses under Info is not ordered
When viewing the Info pane, the Addresses field sometimes updates for me, changing the order of the 4 addresses my node has. The actual addresses don't change, just the order. Maybe this is because they're coming from an unordered datastructure? Could they be sorted before being displayed?

### LINKED ISSUE #600: Pinned hashes don't show up
I have just started using IPFS Desktop, and noticed that my pinned hashes weren't listed in the Pin tab. But when I run `ipfs pin ls` in the command line I get several hashes, including non-default ones. These hashes were pinned before I used IPFS desktop, but shouldn't it still see them?
EDIT: I'd like to add that hashes pinned through IPFS desktop show up in the command line, just not the other way around. I'd like to also say that when I add a file, it doesn't show in the pin tab as well, even though files you add are automatically pinned.

### PR DESCRIPTION
**Pull request by hacdias**
## Related:

- ~Initial Issue: https://github.com/ipfs-shipyard/ipfs-webui/issues/616~
- ~IPFS WebUI PR: https://github.com/ipfs-shipyard/ipfs-webui/pull/618~
- ~[`ipfs-react-components`](https://github.com/hacdias/ipfs-react-components) - common React Components that are used on WebUI and Desktop.~
- Read more on https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/29

## Goals

- [x] Make components as independent as possible
- [x] Remove repo.lock when not running (fix #588)
- [x] Fix #590 by using MFS
- [x] Save pins on MFS (ref.: #597)
- [x] Order addresses on info pane (fix #599)
- [x] Show previously pinned stuff (fix #600)
- [x] Save Screenshots on MFS
- [x] While daemon is turned off, let the user turn it on or close Desktop only.
- [x] Improve Files pane
- [x] Add some basic tests to start the testing journey #50

### CODE REVIEW

**Comment by hacdias** [comment]
image

image

Most of the changes here were under the hood. It now uses MFS for the Files Pane, which does make a lot more sense.

Could you take a look @diasdavid?

**Comment by hacdias** [comment]
Ping @olizilla too 😄

**Comment by diasdavid** [comment]
@hacdias are you storing the files to the mfs root folder or to a folder you create just for this app?

**Comment by hacdias** [comment]
@diasdavid root folder. That way, the user can manage its files and won't be limited by Desktop's scope.

**Comment by olizilla** [comment]
@hacdias is fixing up an issue that showed up on my machine

> 10:35 AM <@hacdias> stats.repo and repo.stat do the same thing
10:35 AM <@hacdias> But on the api they dont have the same handler
10:35 AM <@hacdias> And I only changed one... I'll fix it!

**Comment by olizilla** [comment]
There is a new issue preventing adding files via the files pane. @hacdias is investigating.

**Comment by olizilla** [comment]
File adding now works! ✨ 

Buuuut I then got a little over excited and tired to add a large folder of pictures (around ~2GB). The UI got stuck immediatetly and after about 20s it stalled on:

screen shot 2018-01-25 at 11 24 39

It may well have been adding all the files in the background, but after a few minutes of waiting I gave up, only to have my entire system become unresponsive. Killing all the ipfs processes i could find didn't help, and I eventutually had to hard reboot! Apart from the UI stall, I don't think this is an issue with this PR, but I thought I should flag it as, I'm not going to be the only person who thinks ipfs might be a good way to share all the cat gifs.

What can we do to handle large file drops? Can we pull things off the ui thread so that it can warn the user about what's about to happen if they continue and show progress without freezing if they do?

Much more minor but also suprising was having a default electron start screen appear when restarting. 

screen shot 2018-01-25 at 11 40 51

I assume this is just an artefact of running it in dev mode, but is there a way to make it not happen?

**Comment by olizilla** [comment]
Deleting files seems a little ruthless right now. Did you have any thoughts on how we could make deleteing be un-doable? The button is right next to the copy hash button, so it should either request confirmation of a destructive action, or be easy to undo if they user clicks delete accidentally.

**Comment by hacdias** [comment]
@olizilla :o

> Buuuut I then got a little over excited and tired to add a large folder of pictures (around ~2GB). The UI got stuck immediatetly and after about 20s it stalled on:

Hmm... I have uploaded movies (~2GB) without any problem here.

> Deleting files seems a little ruthless right now. Did you have any thoughts on how we could make deleteing be un-doable?

What if we just for confirmation telling that it is permanent?

> I assume this is just an artefact of running it in dev mode, but is there a way to make it not happen?

I have never seen that before.

**Comment by olizilla** [comment]
Channelling daviddias, master of the _doodles on screenshots_ style feedback...

ipfs-desktop-files-pane

**Comment by hacdias** [comment]
> What do you do?

Yes, I'd like to have a better icon for that 😆 It was already suggested to use a pin but then it could be confused with the Pin tab.

---

I'll do the other updates later today since I won't be home during most of the evening.

**Comment by olizilla** [comment]
> What if we just for confirmation telling that it is permanent?

I think it's worth adding that. I find most confirmation boxes annoying (_"what!? just do what i asked you to do computer!"_) but in the case where people could lose files by accident, it's worth it.

I'll do some more tests of the file upload issue.

**Comment by olizilla** [comment]
Adding a single large file works well. Adding a directory tree with more 1 level seems to cause the super long add time...

**Comment by hacdias** [comment]
image

image

**Comment by hacdias** [comment]
@olizilla @lidel do you feel this branch can be safely merged into master?

**Comment by lidel** [comment]
I smoke-tested under Linux (Debian 9.3) and got this odd error but no logs:

2018-01-26-201024_1098x388_scrot

Note that last release (0.3.0) works fine on the same machine.
Is there something I can do to  provide more diagnostics?

**Comment by hacdias** [comment]
`set DEBUG='desktop'` probably will give you some output. Did you remove `node_modules` first? There are some issues with some dependencies and you probably need to install them again.

**Comment by lidel** [comment]
Cleared `node_modules` + `package-lock.json`, run `install` and `start` with `DEBUG` flag:

```
lycia> DEBUG='desktop' npm start

> ipfs-desktop@0.3.0 start /home/lidel/projects/ipfs-desktop
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies: 2 / 3
✔ Launching Application
  desktop Application is ready +0ms
  desktop Starting daemon +6ms
  desktop Daemon started +3s
  desktop Uncaught Exception: TypeError: Cannot read property 'map' of null
  desktop     at transform (/home/lidel/projects/ipfs-desktop/node_modules/ipfs-api/src/files/ls.js:6:29)
  desktop     at send (/home/lidel/projects/ipfs-desktop/node_modules/ipfs-api/src/utils/send-request.js:208:7)
  desktop     at f (/home/lidel/projects/ipfs-desktop/node_modules/once/once.js:25:25)
  desktop     at streamToValue (/home/lidel/projects/ipfs-desktop/node_modules/ipfs-api/src/utils/stream-to-json-value.js:30:5)
  desktop     at concat (/home/lidel/projects/ipfs-desktop/node_modules/ipfs-api/src/utils/stream-to-value.js:12:22)
  desktop     at ConcatStream.<anonymous> (/home/lidel/projects/ipfs-desktop/node_modules/concat-stream/index.js:36:43)
  desktop     at emitNone (events.js:110:20)
  desktop     at ConcatStream.emit (events.js:207:7)
  desktop     at finishMaybe (/home/lidel/projects/ipfs-desktop/node_modules/readable-stream/lib/_stream_writable.js:607:14)
  desktop     at afterWrite (/home/lidel/projects/ipfs-desktop/node_modules/readable-stream/lib/_stream_writable.js:470:3) +40ms
```

Note that repeated test with yarn instead of npm (`npx yarn@1.3.2 && DEBUG='desktop' npx yarn@1.3.2 start`) and the result is the same.
I'll check the other box in a few mins.

**Comment by hacdias** [comment]
@lidel sorry! I've submited a fix for that (https://github.com/ipfs/js-ipfs-api/pull/680) but it's on js-ipfs-api! To "fix" that temporarily, add a file to the root of your MFS and I promise it will work 😄 

@diasdavid could you take a look at that bugfix, please?

**Comment by lidel** [comment]
Cool, glad my smoke-testing is useful :) I created a file in MFS and it now starts, but .. oh boy, looks like CSS is missing? 

2018-01-26-204215_615x420_scrot

If I scroll, i can find not-styled buttons:

2018-01-26-204228_619x420_scrot

Note that there are  no errors in console nor in `~/.config/ipfs-desktop/logs/*` 🤔 
Did you see it before? `DEBUG='desktop'` shows nothing, so perhaps  this one is caused by something on my end?

**Comment by hacdias** [comment]
@lidel ugh that's weird... and ugly! Really... really... strange. Never happened. Try reloading with CTRL-R. You can open the dev tools with CTRL-SHIFT-I too

**Comment by hacdias** [comment]
Any updates @lidel @olizilla ?

**Comment by lidel** [comment]
@hacdias  updates did not fix it, but I was able to find error related to app.less -- it references files which are not present(?), eg:

> 2018-01-27-195442_2158x472_scrot


```
lycia> grep Pane src/styles/app.less
@import "./components/Pane.less";
@import "./components/PaneContainer.less";

lycia> tree src/styles/ | grep Pane
│   ├── PaneContainer.less
```

I see that app.less includes other files that are not in git. 
I think either one of implicit build steps fail on my machine or not everything is checked in.

**Comment by hacdias** [comment]
@lidel, I'm sorry. Could you try now? (It was beginning with a lower case letter instead of an upper case).

**Comment by hacdias** [comment]
Reallllly nice @lidel 😄 

@diasdavid @olizilla can we merge this?

**Comment by hacdias** [comment]
I'm merging this and if some other issue arises, we can fix it in another PR 😄 Let's move faster 😃

**Comment by Cole128** [comment]
Great update, but it doesn't seem to fix #600 , at least not for me. It still doesn't show hashes I've pinned through the command line. 😞

**Pull request merged**
