### PR TITLE
feat: go-ipfs v0.7.0 and ipfs-webui v2.11.2

### LINKED ISSUE #1639: Downloading a file results in a corrupted archive
- OS: Windows 10 Pro x86_64
 - Version of IPFS Desktop: 0.12.2

**Describe the bug**

Downloading a file results in a corrupted archive.

**To Reproduce**

1. Download something
2. Open it

**Expected behavior**

1. The downloaded file shouldn't be compressed
2. The downloaded file should be usable
3. It would be nice to have progress reporting via https://github.com/ipfs/go-ipfs/issues/7672 🤗

**Screenshots**

image

image

**Additional context**

When I download via BitTorrent, the download files aren't compressed. This makes BitTorrent infinitely easier to download with than IPFS Desktop at the moment.

1. Not everyone is able to open `.tar.gz`
2. I don't have the time to download+compress+decompress 10 GB. Let's just skip the useless compress+decompress part, please!

### PR DESCRIPTION
**Pull request by rafaelramalho19**
cc https://github.com/ipfs/go-ipfs/issues/7560

closes #1639 (by upgrading to webui v2.11.1)

### CODE REVIEW

**Comment by lidel** [comment]
Ugh, I just realized this won't be an easy upgrade:

- `go-ipfs-dep` was deprecated and now we use `go-ipfs` package  (both on NPM)
- `ipfsd-ctl` used for daemon orchestration is ancient and depends on `go-ipfs-dep`  + uses old JS API


I did ipfsd-ctl update recently so it should be still fresh in my mind – I'll take a stab at updating  and comment on this PR later.

**Comment by lidel** [comment]
Ok, it should use the correct go-ipfs binary now for both production and tests.
In the process of removing `go-ipfs-dep` I had to update to the latest `ipfs-http-client` and bump some other dependencies.


### Regression in latest webui: folder import 

Things work as expected apart from Folder upload, which is broken in Electron 8.x:

> 

@rafaelramalho19  Are you able to take a look at this from the  webui side? 

- I remember webui had some Electron-specific handling of folder uploads, seems that recent refactors changed stuff in a way that is no longer compatible with that Electron does. 
- **Perhaps we could remove code specific to Electron and use the same code path  that works in browser?**
  This would save us a lot of headache going forward. 


#### FYI Electron 8 → Electron 10 does not help

I tried to update to the latest Elecron but that is another :hole: :rabbit2:  and with Electron 10 we need to rewrite CORS  handling, so its effectively a separate PR I will submit.

I've set up CORS manually for testing and folder upload is still broken, but the error is different tho:

>

**Review by lidel — APPROVED** [review]
It is ready, thank you @rafaelramalho19 –  we just wait for official 0.7.0 now.

(if you plan to do more dev in ipfs-desktop, it's ok to merge this as-is and then bump to non-RC version before release, if not, ok to park this until final release)

**Comment by lidel** [comment]
@rafaelramalho19 I've bumped this PR to the release version of go-ipfs 0.7.0 and looks good on Linux.

Mind building on mac and windows and confirming there are no surprises?
The usual smoke-test is to start Desktop app  and them upload a directory with cat pictures via embedded WebUI.

**Comment by crcastle** [comment]
@lidel I was wanting to use go-ipfs 0.7.0 with the desktop app on Mac, so I figured I'd do a Mac smoke test for you. Looks good!

`npm ci` on this branch followed by `npm start` and uploading some (Creative Commons licensed) cats works as expected: https://ipfs.io/ipfs/QmRCjyh61g4P31wjTDtdRk9B75CRkiLWPAPPQtQcXHmCs9

Tested with Node 12.16.3 and 14.12.0.

Running `npm ci` with node 14.12.0 produced a bunch of warnings but didn't affect the smoke test steps:

```
<snip>

(node:12955) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12955) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:12955) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12957) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:12957) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
added 1207 packages in 37.726s
```

**Comment by rafaelramalho19** [comment]
@lidel v.2.11.2 is now on this PR 👌

**Review by lidel — CHANGES_REQUESTED** [review]
Looks good, but CI on macOS fails due to Apple notarization:

```
1 package(s) were not uploaded because they had problems:

	/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/FCE68004-143C-41A9-8B85-08020C829FF0/io.ipfs.desktop.itmsp - Error Messages:

		You must first sign the relevant contracts online. (1048)

2020-09-28 15:43:08.319 altool[4208:12324] *** Error: You must first sign the relevant contracts online. (1048)
```

Before this is merged we need to fix notarization so the CI is green.

**Comment by rafaelramalho19** [comment]
@lidel all ready for final reviews 🎉

**Review by lidel — APPROVED** [review]
Sweet! Let's merge, do final eyeballing and if `master` looks good, start release dance.

**Pull request merged**
