### PR TITLE
feat: enable PUBSUB experiment by default

### PR DESCRIPTION
**Pull request by shaikh-shahid**
This is a known and request feature. I don't mind if its released under a branch but lots of people require PUBSUB enabled by default. So here is PR.

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Thanks, @shaikh-shahid! We've got this queued up to discuss in our next weekly triage.

**Comment by shaikh-shahid** [comment]
Awesome @jessicaschilling . Hope it gets merged :)

**Comment by jessicaschilling** [comment]
We've actually got this going under https://github.com/ipfs-shipyard/ipfs-desktop/issues/1647 as part of adding menu items for this and automatic garbage collection -- would you be interested in augmenting your PR to meet that issue's needs?

**Comment by shaikh-shahid** [comment]
Sure @jessicaschilling . Actually I made that suggestion in the PR. I need bit of help in the UI end.

**Comment by jessicaschilling** [comment]
Thanks, @shaikh-shahid! Added a quick mockup of menu item placement in original comment [here](https://github.com/ipfs-shipyard/ipfs-desktop/issues/1647#issue-702650415) -- does that give you what you need to get started?

**Comment by shaikh-shahid** [comment]
Yes, that helps @jessicaschilling . I am currently working on this feature, will submit a PR ASAP. If there is any blocker will surely let you know.

**Comment by olizilla** [comment]
I just tried to enable pubsub on desktop and it was _hard_! I would love a button that let me enable pubsub, and would be totally up for enabling pubsub by default.

**Comment by jessicaschilling** [comment]
Closing as superseded by #1735.

**Pull request closed without merging**
