### PR TITLE
feat: enable ipns over pubsub via settings menu

### PR DESCRIPTION
**Pull request by andrew**
Part of #1647

Very similar approach to #1735

Screenshot 2021-01-20 at 16 08 21

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Hey @andrew, sorry to swoop in on your PR, but as part of this work do you mind changing the menu item `npm on IPFS` to `Use npm on IPFS`? That way everything in the Experiments menu has a verb (and avoids the awkward lowercase of "npm").

Apologies that I didn't catch this under #1735 as it would have been more germane there 😟

**Comment by andrew** [comment]
@jessicaschilling would "Enable npm on IPFS" be more inline with the other experiment options?

**Comment by jessicaschilling** [comment]
@andrew Was leaning toward "Use" for the sake of avoiding visual repetition and because it _might_ be a slightly better word in this case -- i.e. you're not really enabling npm, you're just using it via IPFS delivery. But that's definitely not gospel.

**Comment by andrew** [comment]
Alternatively, you are installing npm on ipfs, which gets used outside of ipfs desktop `Install npm on IPFS`?

**Comment by jessicaschilling** [comment]
@andrew Good point. Yes please 😊

**Comment by andrew** [comment]
@jessicaschilling broke that change out into a separate PR: https://github.com/ipfs-shipyard/ipfs-desktop/pull/1742

**Review by lidel — APPROVED** [review]
Thanks! 

(Moved experiments to pre-existing `experiments.` section of the config)

**Pull request merged**
