### PR TITLE
rename to IPFS Desktop

### PR DESCRIPTION
**Pull request by diasdavid**
Decision has been made \o/ https://github.com/ipfs-shipyard/ipfs-desktop/issues/561

@hacdias mind updating the name in all the places?

### CODE REVIEW

**Comment by hacdias** [comment]
Yup, I'll do that.

**Comment by hacdias** [comment]
@VictorBjelkholm could you help me here with the FOSSA badge?

This link doesn't seem to work: `https://app.fossa.io/projects/git+https://github.com/ipfs-shipyard/ipfs-desktop?ref=badge_large`.

**Comment by hacdias** [comment]
@diasdavid also removed the old changelog.

**Comment by VictorBjelkholm** [comment]
@hacdias I did not add the FOSSA badge, and for me it's kind of useless. Doesn't show the current license and is a closed platform you can't view without login. I would remove it completely.

**Comment by hacdias** [comment]
@VictorBjelkholm oh sorry. I didn't see the blame correctly. I'll remove it then. 

I think it's done @diasdavid

**Pull request merged**
