### PR TITLE
feat: support experimental cohosting

### PR DESCRIPTION
**Pull request by hacdias**
Implements the initial spec of cohosting.

See https://github.com/ipfs-shipyard/cohosting.

This PR requires:

~- https://github.com/olizilla/ipfs-cohost/pull/5~

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by hacdias** [comment]
@lidel probably I'm updating `https://github.com/olizilla/ipfs-cohost` to match our spec and I can just export the update function!

**Comment by hacdias** [comment]
Please see https://github.com/olizilla/ipfs-cohost/pull/5. Let's wait for that

**Comment by hacdias** [comment]
@lidel perhaps this would also be an easy way to apply the syncing part on IPFS Companion.

**Comment by lidel** [comment]
Yes, I like the idea of reusing `ipfs-cohost` for sync/add/remove in ipfs-companion.

**Comment by hacdias** [comment]
Pinging @lidel

**Comment by lidel** [comment]
As agreed during last GUI/Browsers Weekly Call, let's pause this until 2020 Q1.
I don't think we should merge this without  solving https://github.com/ipfs-shipyard/ipfs-cohost/issues/6 first, and we have other priorities in Q4 (#1164).
Need to pick our  battles :)

**Comment by bertrandfalguiere** [comment]
Will this feature be revived some day?

**Comment by lidel** [comment]
Something like this will land, but additional UX work is needed. 
We need a clear user flow where act of pinning  a "website" or "page" via browser extension (https://github.com/ipfs-shipyard/ipfs-companion/issues/888) provides user with control over used storage (lazy vs full pin).

We won't be looking at  this  problem space until https://github.com/ipfs/ipfs-gui/issues/91 lands – I'm closing this for now.

**Pull request closed without merging**
