### PR TITLE
feat: go-ipfs 0.6

### PR DESCRIPTION
**Pull request by lidel**
This PR bumps go-ipfs to 0.6

Before merging:

- [x] test locally with RC1
- [x] wait for final release
- [x] remove `go-ipfs` block from `package.json` and update `go-ipfs-dep` to `0.6.0`

### CODE REVIEW

**Comment by lidel** [comment]
@rafaelramalho19 in spare moment, can you test this branch on macOS and Windows
 (`npm ci && run-s clean:webui build:webui && DEBUG='desktop' npm start`)? 

Most of the stuff is covered by E2E but we dont test directory imports, so just open WebUI, try to add a directory (via button, then via drag & drop).

**Comment by rafaelramalho19** [comment]
Everything is working fine in both macos and windows 😄

**Comment by lidel** [comment]
Bumped to RC7 (https://github.com/ipfs/go-ipfs/issues/7347#issuecomment-645468518), looks good.

**Comment by pomazanbohdan** [comment]
- [ ] wait for final release

**Comment by lidel** [comment]
Waiting for: https://www.npmjs.com/package/go-ipfs-dep

**Comment by lidel** [comment]
@rafaelramalho19 FYSA there will be patch release 0.6.1 next week, 
so its ok to wait and bump this PR then, when you are back next week.

**Comment by lidel** [comment]
@rafaelramalho19 turns out the patch did not land in expected time.

I asked and it is not really relevant to desktop users, so please  merge this PR as-is, and also new webui from #1455 Then check if `master` works fine on mac/windows and if all good ship a new 0.11.5

**Pull request merged**
