### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by hacdias**
License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by olizilla** [comment]
@hacdias i don't see the travis builds in the details list for this PR. What happened?

screenshot 2019-02-12 at 10 21 51

**Comment by hacdias** [comment]
image

Hm?

**Comment by hacdias** [comment]
image

**Comment by olizilla** [comment]
oh github. that is weird.

**Pull request merged**
