### PR TITLE
Start addressing the tests

### PR DESCRIPTION
**Pull request by hacdias**
Ref.: #50 

Starting by testing the components directory.

This uses `feat/components` as base. Can only be merged after #596

### CODE REVIEW

**Comment by hacdias** [comment]
With the current configuration, I'm getting this:

```
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

@VictorBjelkholm do you think you could help with this? `nyc` doesn't seem to be working correctly. I added the configuration to `package.json` and the `instabul` plugin to Babel.

**Comment by VictorBjelkholm** [comment]
I think you should start with setting up tests with spectron/acceptance testing. Main idea is to just make sure the core UI functionality works. Then you can start adding unit tests for making sure every detail is working. About coverage, we still working on making sure the secret management in Jenkins is stable and secure. So not gonna do that from jenkins just yet.

Another point, in general you should avoid having files with big and small letters, as you'll hit confusing errors when you name some file `HelloWorld.md` and on the OS you're developing you can load it as `helloworld.js` but it won't work on others (or vice-versa). It's  easier to always have lower-case naming and use underscore instead.

**Comment by hacdias** [comment]
> I think you should start with setting up tests with spectron/acceptance testing. Main idea is to just make sure the core UI functionality works.

I'd like to do that but it isn't simply working... yet! Our electron is using some pre-compilers for LESS and Babel and I wasn't still able to decipher how to use that with Spectron.

> Another point, in general you should avoid having files with big and small letters...

I'm just using CamelCase for files with components to follow React's best practices, but I can change that. Should I?

**Comment by hacdias** [comment]
@VictorBjelkholm I'm trying to make this simply start the app and nothing seems to happen. I'll increase the timeout for something like 10 mins and see what happens.

image

Ref.: https://github.com/electron-userland/electron-compile/issues/178

**Comment by hacdias** [comment]
Many conflicts. 

- [ ] Fix after #596 gets merged.

**Comment by hacdias** [comment]
This tests got merged on #596. Keep working on #596

**Pull request closed without merging**
