### PR TITLE
chore: go-ipfs v0.4.23

### PR DESCRIPTION
**Pull request by lidel**
- [x] Smoke-test v0.4.23-rc1  
- [x] Fix snap build on Linux
- [x] Switch CI to the current Node LTS
- [x] Switch this PR to v0.4.23 when ships (https://github.com/ipfs/go-ipfs/issues/6837)
- [ ] Fix E2E tests on CI (Mac)

### CODE REVIEW

**Comment by hacdias** [comment]
Shouldn't we get the new CTL too?

**Comment by lidel** [comment]
@hacdias the old CTL works fine, let's keep changes in this bugfix release minimal.

(switch to new CTL is tracked in https://github.com/ipfs-shipyard/ipfs-desktop/pull/1302, its parked for now, but we will get to that eventually, not a high priority).

**Comment by lidel** [comment]
@hacdias good question. Does `npm run test:e2e` break  on your Mac, or is this problem limited to CI?

**Comment by lidel** [comment]
@hacdias we should make v0.10.3 release with this, but I don't want to distract you in the every time we need to make a release. Could you tech me how to do a release? :-)
 

Is the process documented at https://github.com/ipfs-shipyard/ipfs-desktop#releasing still valid? If not, mind updating it?

Can you give me some tips&access to do:
- Update Homebrew Cask.
- Update Chocolatey package.

**Comment by hacdias** [comment]
@lidel I won't be available this week (will be without a computer). The process is still valid. Anyone can update the cask, just follow the linked tutorial :)

For the chocolatey: please create an account at https://chocolatey.org/ first and lemme know your username/email.

**Comment by lidel** [comment]
@hacdias done, I am https://chocolatey.org/profiles/lidel

**Comment by hacdias** [comment]
@lidel just added you as a maintainer. It says it's pending approval (?).

**Pull request merged**
