### PR TITLE
feat(un): decouple webui [META] [THOUGHT]

### PR DESCRIPTION
**Pull request by hacdias**
See #1389.

This is my attempt at decoupling IPFS Desktop from Web UI. It is not finished and I won't work more on it unless we all agree we should move forward on this.

This basically removes the Web UI window and when you click 'Status' or 'Files' you're just pointed to your default browser, opening the Web UI.

image

The Preferences (or Settings for non-macOS users) are all checkboxes. Clicking on them should be enough to enable or disable them. Some (not implemented) should show a dialog explaining what they actually do and ask the user if they really want to proceed.

On the Web UI side, a lot of simplifications can be made with this!

### CODE REVIEW

**Comment by hacdias** [comment]
@lidel @jessicaschilling @autonome I would love your input on this 😃

**Comment by jessicaschilling** [comment]
Thought: Regardless of the degree to which we do/don't kill off the Electron standalone window in favor of moving into the browser -- moving those desktop-only settings out of the "Settings" screen and into the menubar makes a lot of sense. There's some linguistic stuff that probably needs to be refined (basically, we need to be explicitly clear about when "settings" means "IPFS config" and when it means "app settings"), but overall this makes a ton of sense, particularly for people who switch between Desktop and WebUI: right now we are giving them two different settings screens and that makes it really hard to remember where you do what.

If we do go in the direction of "IPFS Desktop" really just meaning "IPFS Menubar App", this sort of implies that we're committing to the path of OS integration over standalone apps ... which I'm all in favor of, and in any case matches industry trends for cloud file sharing. This sounds fantastic on the surface, but maybe we want to have a dedicated conversation about this as whether it is, indeed, our strategic direction.

**Comment by lidel** [comment]
Quick feedback: keep PRs small. Easier to discuss, easier to review, less mistakes :+1: 


- **limit the scope of this PR to the Settings cleanup**   
  - focus on decoupling ipfs-desktop's Settings from ipfs-webui screen and moving them to intuitive menu items
  - keep bundling ipfs-webui and keep opening it in Electron for now
   (switching to browser should be separate PR)
- menu actions that are ON/OFF should indicate clear action (start with verb?):
  - examples: "Enable npm-on-ipfs", "Enable command line tools" etc

**Comment by hacdias** [comment]
@lidel that's actually what I thought after doing this haha. I'm going to do another PR with the preferences section only then!

**Comment by hacdias** [comment]
I'll close this PR.

**Pull request closed without merging**
