### PR TITLE
feat: update zh-TW locales

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Comment by lidel** [comment]
Thank you for contributing translation @bluelovers ! 

To avoid duplicated work, we don't accept direct PRs with locales.
Please submit translations using Transifex project at https://www.transifex.com/ipfs/ipfs-desktop/ 

(Let me know your Transifex account name, I will add you to the Russian translation team)

We synchronize translations with Transifex before each release, as you can see in #1347. 
You can find more information at [/docs/localization-notes.md](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/docs/localization-notes.md) and [ipfs/i18n](https://github.com/ipfs/i18n).

**Comment by bluelovers** [comment]
hmm, i think need fix link in readme

Transifex link in readme is 404, that is why i  use pr

**Comment by lidel** [comment]
@bluelovers which link returned 404 for you? 
https://www.transifex.com/ipfs/ipfs-desktop/ is public and works fine

**Comment by bluelovers** [comment]
image

https://www.transifex.com/ipfs/ipfs-desktop/translate/

image

**Comment by lidel** [comment]
@bluelovers wow this is interesting, for me the /translate link redirects to the login page at https://www.transifex.com/signin/?next=/ipfs/ipfs-desktop/translate/

Are you able to check if you can login via above link?

**Comment by bluelovers** [comment]
login and logout both is 404 at that link

**Comment by lidel** [comment]
@bluelovers very odd. Are you behind The Great Firewall of China?

**Comment by bluelovers** [comment]
nope

https://www.transifex.com/ipfs/ipfs-desktop/translate/ <== 404
https://www.transifex.com/ipfs/ipfs-desktop/ <== ok

**Comment by lidel** [comment]
How about https://www.transifex.com/signup/?join_project=ipfs-desktop ?

**Comment by bluelovers** [comment]
i think is not, it redirect to
https://www.transifex.com/nodebb/nodebb/dashboard/

**Comment by lidel** [comment]
@bluelovers try logging out of Transifex and logging in again, then open https://www.transifex.com/ipfs/ipfs-desktop/translate/
You should have access to zh-TW now.

**Comment by bluelovers** [comment]
https://www.transifex.com/ipfs/ipfs-desktop/translate/ this link only work when add into team

**Comment by lidel** [comment]
Ah.. yes, that is what was missing.
Thank you for your patience and contributions!

**Comment by bluelovers** [comment]
other ipfs readme has same issue too

**Pull request closed without merging**
