### PR TITLE
feat: enable pubsub via settings menu

### PR DESCRIPTION
**Pull request by andrew**
Part of https://github.com/ipfs-shipyard/ipfs-desktop/issues/1647

Screenshot 2021-01-19 at 13 48 38

Adds a menu preference option to enable pubsub which adds a flag to the ipfsd-ctl options for startup.

Question: should this prompt a restart, given that the setting won't take effect until ipfs has been been restarted?

Bug: I'm getting the enabled/disabled message logged twice when clicking on the menu item, not quite sure why :
```
$ npm start

> ipfs-desktop@0.13.2 start
> cross-env NODE_ENV=development electron .

2021-01-19T16:19:06.988Z info: [meta] logs can be found on /Users/andrewnesbitt/Library/Application Support/IPFS Desktop
2021-01-19T16:19:10.560Z info: [web ui] window ready
2021-01-19T16:19:10.560Z info: [tray] starting
2021-01-19T16:19:10.607Z info: [tray] started
2021-01-19T16:19:10.608Z info: [ipfsd] start daemon STARTED
2021-01-19T16:19:10.937Z info: [daemon] removing api file
2021-01-19T16:19:11.954Z info: [ipfsd] start daemon FINISHED 1.3460042808055879s
2021-01-19T16:19:11.957Z info: [launch on startup] unavailable during development
2021-01-19T16:19:11.972Z info: [pubsub] disabled
2021-01-19T16:19:11.975Z info: [ipfs on path] no action taken
2021-01-19T16:19:17.770Z info: [pubsub] enabled
2021-01-19T16:19:17.791Z info: [pubsub] enabled
2021-01-19T16:22:36.969Z info: [pubsub] disabled
2021-01-19T16:22:37.000Z info: [pubsub] disabled
```

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@lidel, can you please have a look as you're able?

**Review by lidel — APPROVED** [review]
@andrew looks and works great! :heart: 

- Moved PubSub toggle to experiments, because it is marked as one in go-ipfs docs:
  https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipfs-pubsub
- Fixed the duplicated message in https://github.com/ipfs-shipyard/ipfs-desktop/pull/1735/commits/47f83cb5ce2e5d0a578932b37328f1e7f68a784e
- We have to restart go-ipfs to have the flagg applied, so I've added code that triggers restart via `ipcMain.emit('ipfsConfigChanged')`
  - While  doing that found a bug in logic responsible for restarting the node on config changes. Took me a while to realize where the duplicated process comes from.
  - Ended up bumping `ipfsd-ctl`, as the bug seems to be fixed in https://github.com/ipfs/js-ipfsd-ctl/pull/554
  - :point_right:  It works as expected on Linux, mind testing on macOS before I merge this? Toggling should restart the node.

**Comment by olizilla** [comment]
What if we _enabled pubsub by default_ 🙀 💞

**Comment by lidel** [comment]
@olizilla   if we do it here, we also should enable it in Brave.
Meanwhile, on the pubsub track there [are open issues](https://github.com/ipfs/go-ipfs/search?q=pubsub&state=open&type=issues), would you pull the lever? :trollface:        :steam_locomotive: :train::train::train:  

I'd rather wait for https://github.com/ipfs/go-ipfs/issues/5383 and https://github.com/ipfs/go-ipfs/issues/6621   :sweat_smile:

**Comment by andrew** [comment]
Wow, thanks for the updates @lidel, I was only expecting some pointers, not just for you to finish the pr!

Tested on macOS, working as expected, restarting correctly and such 🎉

**Comment by lidel** [comment]
@andrew I simplified it a bit (run out of coffee yesterday), mind checking again? 
I want to ship this this or next week because of the bug we've  fixed in this PR :)

**Comment by andrew** [comment]
Retested on macOS, still looking good 👍

**Pull request merged**
